language: ruby
rvm:
- 2.2.0
sudo: false
script: bundle exec rake deploy
env:
  global:
    secure: EJdFWsBwv6OBoAUMMN5Fc9o+FuHgzAotHT9jIfXVoRw07iHl2zgEfhZZ8rAV47iy39vYnzI5VGNrSyt7ygDVyklJ3gmrpt+fOhd23XL30f/2MkcVcZUkCXvSYA9F7dHXlljMvZUuKcx+6uHYuA6GoVHzr+l6tvDkiIcV31ccY0fH+o4D6yPkvC+947TO3NalRdNNlpBdz2UxDTE+pzk13u++fLnzkHTFcz6EvUwki/KD/QlqqmeC6oiWgOVN8EFKO/5v+Tn8BOpNsXyO3HtbPAkuNeSdcVKWHmaAUfiMXBVKc7c3QRjuG2AxhsU5Kf+cXvbaWE8lkojPVGdB2x2MSEvGEUxChsp/AfJjBsXdZM447JorIS5Hr09dt+diRlMHXgC9X7IGCzuDg+gq+8TMIvTVH47dET6pnOmYqLZC10pIove1VacHCbn0t6NCnrvzl+kfM3R9rmcUSeqQnJH+vcgnxEa4X32TP8DRJEqk/lCQgDqmB/2uTFJMR3QHhEQt20OJlz6Ho9KCwi/wa3MBld7zJE64N5eoBBop/1ve4byRjldrxMe2AGIoPl2gdIJSAnOuDuVyEscBN1qfsB+MEKvPWbxwrknajaJaKuN30bk1F/WXngdVBckLd1euk1JQlZk+ribA6yhjMyc/WjOhZL4wbZ1jcddFOgFH0G3AUaM=
